### ISSUE TITLE
Would be nice if it had an error callback or threw an exception if it's fed a bad PDF

### ISSUE THREAD

**Issue by kenyee** [Dmitry-Borodin/pdfview-android#19]
Noticed a bad backend had an error and was sending back HTML instead of the PDF.  All the PdfView displayed was a blank page.

Would be nice if it threw an exception or had some other way of reporting an error.

**Comment by Dmitry-Borodin** [comment]
That is doable - SubsamplingScaleImageView.java:1578 catches such errors. We can report them to callback if callback is set.

Do you mainly need it for analytics reason? Because I suppose usually you cannot do anything about it in the app, right?
If so, doesn't it make sense to tell backend to send analytics events if they cannot properly process the request?

**Comment by kenyee** [comment]
Yep, can't do anything about it in the app...server might just be having a bad day (this one was which is why I noticed because I added handling for network exceptions).  It fed HTML over when I requested a PDF.  Then I fed it to the pdfview :)

**Comment by Dmitry-Borodin** [comment]
Actually you can use setOnImageEventListener() on the view, you can set DefaultOnImageEventListener if you don't want to override all methods. onImageLoadError() is the one you are looking for.
I will create another issue for cleaning up this API, since we don't use staff like preview for pdf and so on, SubsamplingScaleImageView implementation can be simplified for this project.

**Comment by Dmitry-Borodin** [comment]
@kenyee I will close the issue, please feel free to reopen if you'll have any questions.
