### ISSUE TITLE
Add 'sources' such as '.fromBytes( byte[] )'

### ISSUE THREAD

**Issue by mws-rmain** [Dmitry-Borodin/pdfview-android#21]
Similar to [this PDF Viewer](https://github.com/barteksc/AndroidPdfViewer)...
I want to generate a PDF entirely in memory instead of writing to file, to provide a 'preview' of what will be written.
Or course, I could write to a file, view it & delete it afterward, but generation in memory is a much more eloquent solution.

**Comment by Dmitry-Borodin** [comment]
Hi, thank you for taking a time to share your idea.

Android platform PdfRenderer requires ParcelFileDescription which is a wrapper around File and doesn't work with byte array. This is what we use here under the hood.

So I don't see a reason to add big workaround for this use case to a library.  Better to keep it tiny since I believe this is an edge case.

**Comment by mws-rmain** [comment]
Thanks for the response, Dmitry.

As for this being an 'edge-case': My work around is to write my generated PDF from memory to a file, pass this file to pdf-view, which then reads the file back into memory for processing & display. When finished 'pre-viewing' the PDF file, pdf-view closes, and I delete the file. 

Far from 'clean', but it works.

**Comment by Dmitry-Borodin** [comment]
This is how android framework PdfRenderer intended to work. I believe most of the usecases of the library is when you show pregenerated pdf, not generated just now.
